name: Playwright Java Tests (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§© Checkout code
        uses: actions/checkout@v4

      - name: â˜• Set up Java 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven


      - name: ğŸ›  Install system dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y \
           libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
           libxkbcommon0 libgbm1 libpango-1.0-0 libcairo2 \
           libasound2 libxshmfence1 libxrandr2 libgtk-3-0 \
           libdrm2 libxdamage1 libxcomposite1 libxfixes3 libxext6 libxi6


      - name: âš™ï¸ Install Playwright browsers
        run: |
          npx playwright install --with-deps chromium

      - name: ğŸ§± Build project
        run: mvn clean install -DskipTests=true

      - name: ğŸ§ª Run TestNG tests
        env:
          HEADED: true
        run: |
          echo "Running Playwright tests..."
          mvn test -Dheadless=true

      - name: ğŸ“Š Generate Allure report
        if: always()
        run: mvn allure:report

      - name: ğŸ“¦ Upload Allure results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: ğŸ“¦ Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
